services:
  - type: worker
    name: quote-twitter-bot
    env: python
    region: singapore  # fastest for India
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true

    envVars:
      X_API_KEY: 
        fromSecret: X_API_KEY
      X_API_KEY_TW:
        fromSecret: X_API_KEY_TW
      X_API_SECRET:
        fromSecret: X_API_SECRET
      X_ACCESS_TOKEN:
        fromSecret: X_ACCESS_TOKEN
      X_ACCESS_SECRET:
        fromSecret: X_ACCESS_SECRET
      BOT_TOKEN:
        fromSecret: BOT_TOKEN
      ADMIN_ID:
        fromSecret: ADMIN_ID
